repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks: 
    -  id: check-merge-conflict
    -  id: detect-aws-credentials
       args: ["--allow-missing-credentials"]
    -  id: detect-private-key
    -  id: debug-statements
    -  id: name-tests-test
       files: '((etl|lib)\/.+?\/test\/.+\.py)|(integration_test\/.+.py)'
  - repo: local
    hooks:
      -  id: bandit
         name: bandit
         stages: [commit]
         entry: bandit
         args: ["--recursive", "--exclude", "**/*test.py"]
         language: system
         types: [python]

      -  id: isort
         name: isort
         stages: [commit]
         entry: isort
         args: ["--check-only", "."]
         language: system
         types: [python]

      -  id: black
         name: black
         stages: [commit]
         entry: black
         args: ["--check", "."]
         language: system
         types: [python]

      -  id: flake8
         name: flake8
         stages: [commit]
         entry: flake8
         args: ["."]
         language: python
         types: [python]

      -  id: mypy
         name: mypy
         stages: [commit]
         entry: mypy
         language: system
         types: [python]

      -  id: pylint
         name: pylint
         stages: [commit]
         entry: pylint
         args: ["multiprocess_ftp"]
         language: system
         types: [python]

      -  id: pydocstyle
         name: pydocstyle
         stages: [commit]
         entry: pydocstyle
         args: ["multiprocess_ftp"]
         language: system
         types: [python]
